export type Attribute = {
  name: string;
  isCongenital: boolean;
  isSecret: boolean;
  basicLooks: number;
  basicTechnic: number;
  basicMental: number;
  fluctuatedLooks: number;
  fluctuatedTechnic: number;
  fluctuatedMental: number;
};
export const attributes: Attribute[] = [
  {
    name: '巨乳',
    isCongenital: true,
    isSecret: false,
    basicLooks: 1000,
    basicTechnic: 600,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 200,
    fluctuatedMental: 0,
  },
  {
    name: '貧乳',
    isCongenital: true,
    isSecret: false,
    basicLooks: -600,
    basicTechnic: -600,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 0,
  },
  {
    name: '安産型',
    isCongenital: true,
    isSecret: false,
    basicLooks: 1000,
    basicTechnic: 200,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 100,
    fluctuatedMental: 0,
  },
  {
    name: '脚線美',
    isCongenital: true,
    isSecret: false,
    basicLooks: 1000,
    basicTechnic: 200,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 100,
    fluctuatedMental: 0,
  },
  {
    name: '玉の肌',
    isCongenital: true,
    isSecret: false,
    basicLooks: 1000,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 200,
    fluctuatedTechnic: 100,
    fluctuatedMental: 0,
  },
  {
    name: '筋肉質',
    isCongenital: true,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 100,
    fluctuatedTechnic: 200,
    fluctuatedMental: 0,
  },
  {
    name: '着やせ',
    isCongenital: true,
    isSecret: false,
    basicLooks: 1000,
    basicTechnic: 200,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 100,
    fluctuatedMental: 0,
  },
  {
    name: '名器',
    isCongenital: true,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 1000,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 300,
    fluctuatedMental: 0,
  },
  {
    name: '外傷',
    isCongenital: false,
    isSecret: false,
    basicLooks: -1000,
    basicTechnic: -600,
    basicMental: -1000,
    fluctuatedLooks: -300,
    fluctuatedTechnic: -300,
    fluctuatedMental: -300,
  },
  {
    name: '骨折',
    isCongenital: false,
    isSecret: false,
    basicLooks: -600,
    basicTechnic: -1000,
    basicMental: -1000,
    fluctuatedLooks: -200,
    fluctuatedTechnic: -300,
    fluctuatedMental: -300,
  },
  {
    name: '車椅子',
    isCongenital: false,
    isSecret: false,
    basicLooks: -200,
    basicTechnic: -1000,
    basicMental: -1000,
    fluctuatedLooks: -200,
    fluctuatedTechnic: -300,
    fluctuatedMental: -300,
  },
  {
    name: '低血圧',
    isCongenital: true,
    isSecret: false,
    basicLooks: -200,
    basicTechnic: -200,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: -200,
    fluctuatedMental: -100,
  },
  {
    name: '病弱',
    isCongenital: false,
    isSecret: false,
    basicLooks: -200,
    basicTechnic: -1000,
    basicMental: -1000,
    fluctuatedLooks: -300,
    fluctuatedTechnic: -200,
    fluctuatedMental: -200,
  },
  {
    name: '失明',
    isCongenital: false,
    isSecret: false,
    basicLooks: -200,
    basicTechnic: -600,
    basicMental: -1000,
    fluctuatedLooks: 0,
    fluctuatedTechnic: -200,
    fluctuatedMental: -200,
  },
  {
    name: 'タトゥ',
    isCongenital: false,
    isSecret: false,
    basicLooks: -1000,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 0,
  },
  {
    name: 'ピアス',
    isCongenital: false,
    isSecret: false,
    basicLooks: -200,
    basicTechnic: 200,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 100,
    fluctuatedMental: 0,
  },
  {
    name: '敏感',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 1000,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 300,
    fluctuatedMental: 0,
  },
  {
    name: '体臭',
    isCongenital: false,
    isSecret: false,
    basicLooks: -600,
    basicTechnic: -600,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: -200,
    fluctuatedMental: 0,
  },
  {
    name: '令嬢',
    isCongenital: true,
    isSecret: false,
    basicLooks: 1000,
    basicTechnic: -600,
    basicMental: -600,
    fluctuatedLooks: -100,
    fluctuatedTechnic: -100,
    fluctuatedMental: -300,
  },
  {
    name: '有名人',
    isCongenital: true,
    isSecret: false,
    basicLooks: 1000,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: -100,
    fluctuatedTechnic: 0,
    fluctuatedMental: -200,
  },
  {
    name: '委員長',
    isCongenital: true,
    isSecret: false,
    basicLooks: 200,
    basicTechnic: 0,
    basicMental: 200,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 0,
  },
  {
    name: '優等生',
    isCongenital: true,
    isSecret: false,
    basicLooks: 200,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 100,
    fluctuatedMental: 0,
  },
  {
    name: '運動部',
    isCongenital: true,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 200,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 0,
  },
  {
    name: '補導歴',
    isCongenital: true,
    isSecret: false,
    basicLooks: -200,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 200,
  },
  {
    name: '生活難',
    isCongenital: true,
    isSecret: false,
    basicLooks: -200,
    basicTechnic: 0,
    basicMental: 200,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 200,
  },
  {
    name: '彼氏有',
    isCongenital: true,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 200,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: -100,
  },
  {
    name: '彼女有',
    isCongenital: true,
    isSecret: false,
    basicLooks: 200,
    basicTechnic: -1000,
    basicMental: -1000,
    fluctuatedLooks: 0,
    fluctuatedTechnic: -300,
    fluctuatedMental: -300,
  },
  {
    name: '既婚',
    isCongenital: true,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 200,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 0,
  },
  {
    name: '経産婦',
    isCongenital: true,
    isSecret: false,
    basicLooks: -200,
    basicTechnic: 200,
    basicMental: 200,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 0,
  },
  {
    name: '人気者',
    isCongenital: true,
    isSecret: false,
    basicLooks: 600,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 0,
  },
  {
    name: '王子様',
    isCongenital: false,
    isSecret: false,
    basicLooks: 600,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 0,
  },
  {
    name: '愛嬌',
    isCongenital: false,
    isSecret: false,
    basicLooks: 600,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 200,
    fluctuatedMental: 0,
  },
  {
    name: 'クール',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 200,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 200,
  },
  {
    name: '無口',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: -200,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: -200,
    fluctuatedMental: 0,
  },
  {
    name: '強情',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 1000,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 200,
  },
  {
    name: '前向き',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 600,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 200,
  },
  {
    name: '一途',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 600,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 200,
  },
  {
    name: '照れ屋',
    isCongenital: false,
    isSecret: false,
    basicLooks: 200,
    basicTechnic: -200,
    basicMental: -200,
    fluctuatedLooks: 0,
    fluctuatedTechnic: -100,
    fluctuatedMental: -200,
  },
  {
    name: '臆病',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: -600,
    basicMental: -600,
    fluctuatedLooks: 0,
    fluctuatedTechnic: -100,
    fluctuatedMental: -200,
  },
  {
    name: '従順',
    isCongenital: false,
    isSecret: false,
    basicLooks: 200,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 100,
    fluctuatedTechnic: 200,
    fluctuatedMental: 200,
  },
  {
    name: '正義感',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 200,
    fluctuatedLooks: 0,
    fluctuatedTechnic: -100,
    fluctuatedMental: -200,
  },
  {
    name: '真面目',
    isCongenital: false,
    isSecret: false,
    basicLooks: 200,
    basicTechnic: 0,
    basicMental: -200,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 200,
    fluctuatedMental: -100,
  },
  {
    name: '小悪魔',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 600,
    basicMental: 600,
    fluctuatedLooks: 100,
    fluctuatedTechnic: 100,
    fluctuatedMental: 200,
  },
  {
    name: '高飛車',
    isCongenital: false,
    isSecret: false,
    basicLooks: -200,
    basicTechnic: -200,
    basicMental: 600,
    fluctuatedLooks: 0,
    fluctuatedTechnic: -100,
    fluctuatedMental: 100,
  },
  {
    name: '潔癖',
    isCongenital: false,
    isSecret: false,
    basicLooks: 200,
    basicTechnic: -1000,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: -300,
    fluctuatedMental: -300,
  },
  {
    name: '無垢',
    isCongenital: false,
    isSecret: false,
    basicLooks: 200,
    basicTechnic: -200,
    basicMental: 0,
    fluctuatedLooks: 200,
    fluctuatedTechnic: 100,
    fluctuatedMental: 300,
  },
  {
    name: 'えっち',
    isCongenital: false,
    isSecret: false,
    basicLooks: 200,
    basicTechnic: 1000,
    basicMental: 0,
    fluctuatedLooks: 200,
    fluctuatedTechnic: 300,
    fluctuatedMental: 300,
  },
  {
    name: '変態',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 1000,
    basicMental: 0,
    fluctuatedLooks: -100,
    fluctuatedTechnic: 300,
    fluctuatedMental: 300,
  },
  {
    name: '癒し系',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 100,
    fluctuatedTechnic: 200,
    fluctuatedMental: 200,
  },
  {
    name: 'ゆるい',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: -600,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: -300,
    fluctuatedMental: 0,
  },
  {
    name: '不思議',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 200,
  },
  {
    name: '心の闇',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: -200,
    fluctuatedTechnic: 100,
    fluctuatedMental: -200,
  },
  {
    name: '自虐的',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: -200,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 100,
    fluctuatedMental: -300,
  },
  {
    name: 'サイコ',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 200,
    basicMental: 1000,
    fluctuatedLooks: -200,
    fluctuatedTechnic: 100,
    fluctuatedMental: 300,
  },
  {
    name: '上品',
    isCongenital: false,
    isSecret: false,
    basicLooks: 600,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: -100,
    fluctuatedMental: -200,
  },
  {
    name: '家庭的',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 0,
  },
  {
    name: '魔性',
    isCongenital: false,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 200,
    fluctuatedTechnic: 200,
    fluctuatedMental: 300,
  },
  // マニュアルに記載されていない隠し属性
  {
    name: '二形',
    isCongenital: true,
    isSecret: false,
    basicLooks: -1000,
    basicTechnic: 600,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 300,
    fluctuatedMental: 0,
  },
  {
    name: '男の娘',
    isCongenital: true,
    isSecret: false,
    basicLooks: -1000,
    basicTechnic: 200,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 0,
  },
  {
    name: '泥中蓮',
    isCongenital: true,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 300,
    fluctuatedTechnic: -300,
    fluctuatedMental: 0,
  },
  {
    name: '無双',
    isCongenital: true,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 400,
    fluctuatedMental: 0,
  },
  {
    name: '無相',
    isCongenital: true,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 400,
    fluctuatedTechnic: 0,
    fluctuatedMental: 0,
  },
  {
    name: '無想',
    isCongenital: true,
    isSecret: false,
    basicLooks: 0,
    basicTechnic: 0,
    basicMental: 0,
    fluctuatedLooks: 0,
    fluctuatedTechnic: 0,
    fluctuatedMental: 800,
  },
] as const;
